FROM python:3.10-slim

WORKDIR /app

COPY proxy_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY proxy_service/proxy_main.py .

EXPOSE 8001

CMD ["uvicorn", "proxy_main:app", "--host", "0.0.0.0", "--port", "8001"]